[project]
name = "anime-utils"
version = "1.1.0"
description = "Fetch data from multiple anime resources"
readme = "README.md"
authors = [{ name = "Vasiliy Mozhaev", email = "mozhay2005@gmail.com" }]
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.2",
    "aiohttp-socks>=0.11.0",
    "aiolimiter>=1.2.1",
    "aiosqlite>=0.22.0",
    "docstring-parser>=0.17.0",
    "fastmcp>=2.14.1",
    "parsel>=1.10.0",
    "pydantic-settings[yaml]>=2.12.0",
    "rapidfuzz>=3.14.3",
    "tenacity>=9.1.2",
]

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "debugpy>=1.8.18",
    "ipykernel>=7.1.0",
    "pip>=25.3",
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.9",
]

[tool.ruff.lint]
select = ["E", "F", "W", "B", "Q", "I", "RUF", "FAST"]

[tool.ruff]
line-length = 120

[project.scripts]
anime-utils = "anime_utils.cli:main"
